"""empty message

Revision ID: 0a88ad0f29e0
Revises: 298bbf22bdb8
Create Date: 2017-04-04 12:59:27.234320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a88ad0f29e0'
down_revision = '298bbf22bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewery', sa.Column('brewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_brewery_person', 'brewery', 'person', ['brewer_id'], ['id'])
    op.add_column('location', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_location_person', 'location', 'person', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_location_person', 'location', type_='foreignkey')
    op.drop_column('location', 'manager_id')
    op.drop_constraint('fk_brewery_person', 'brewery', type_='foreignkey')
    op.drop_column('brewery', 'brewer_id')
    # ### end Alembic commands ###
