"""empty message

Revision ID: 298bbf22bdb8
Revises: b976e7a7dc35
Create Date: 2017-04-02 13:11:00.655727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298bbf22bdb8'
down_revision = 'b976e7a7dc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('admin', sa.Boolean()))
    op.add_column('person', sa.Column('brewer', sa.Boolean()))
    op.add_column('person', sa.Column('manager', sa.Boolean()))
    op.execute('UPDATE person SET admin=False, brewer=False, manager=False')
    op.alter_column('person', 'admin', nullable=False)
    op.alter_column('person', 'brewer', nullable=False)
    op.alter_column('person', 'manager', nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'manager')
    op.drop_column('person', 'brewer')
    op.drop_column('person', 'admin')
    # ### end Alembic commands ###
