"""empty message

Revision ID: 5b0c653a64b3
Revises: 3e421d588b08
Create Date: 2017-03-30 12:30:56.118960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0c653a64b3'
down_revision = '3e421d588b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tap', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tap', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tap', type_='foreignkey')
    op.drop_column(u'tap', 'location_id')
    op.drop_table('location')
    # ### end Alembic commands ###
