"""empty message

Revision ID: 602fa0cf66f9
Revises: 34223fdff008
Create Date: 2017-08-23 16:31:56.219812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602fa0cf66f9'
down_revision = '34223fdff008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'private')
    # ### end Alembic commands ###
