"""empty message

Revision ID: b4bcea5528b6
Revises: bf1741a1b881
Create Date: 2017-04-15 22:33:52.305530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bcea5528b6'
down_revision = 'bf1741a1b881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brewers',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('brewery_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brewery_id'], ['brewery.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'brewery_id')
    )
    op.create_table('managers',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'location_id')
    )
    op.drop_constraint(u'fk_brewery_person', 'brewery', type_='foreignkey')
    op.drop_column(u'brewery', 'brewer_id')
    op.drop_constraint(u'fk_location_person', 'location', type_='foreignkey')
    op.drop_column(u'location', 'manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'location', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fk_location_person', 'location', 'person', ['manager_id'], ['id'])
    op.add_column(u'brewery', sa.Column('brewer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fk_brewery_person', 'brewery', 'person', ['brewer_id'], ['id'])
    op.drop_table('managers')
    op.drop_table('brewers')
    # ### end Alembic commands ###
