"""empty message

Revision ID: bf1741a1b881
Revises: 0a88ad0f29e0
Create Date: 2017-04-14 21:46:47.950176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1741a1b881'
down_revision = '0a88ad0f29e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('person', sa.Column('lastname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'lastname')
    op.drop_column('person', 'firstname')
    # ### end Alembic commands ###
