"""empty message

Revision ID: c538b32be5c0
Revises: 881ebd2670dd
Create Date: 2017-03-30 21:44:53.158229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c538b32be5c0'
down_revision = '881ebd2670dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tap', sa.Column('price_jug', sa.Float(), nullable=True))
    op.add_column('tap', sa.Column('price_pint', sa.Float(), nullable=True))
    op.add_column('tap', sa.Column('price_tulip', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tap', 'price_tulip')
    op.drop_column('tap', 'price_pint')
    op.drop_column('tap', 'price_jug')
    # ### end Alembic commands ###
